enum PLAY_LIST_TYPE {
  CHILL = "CHILL",
  GAMING = "GAMING",
  WORKING = "WORKING",
  SPLEEPING = "SPLEEPING",
  PARTY = "PARTY",
  UNKNOW = "UNKNOW",
}

export const playlistTypeArray: PLAY_LIST_TYPE[] = [
  PLAY_LIST_TYPE.CHILL,
  PLAY_LIST_TYPE.GAMING,
  PLAY_LIST_TYPE.WORKING,
  PLAY_LIST_TYPE.SPLEEPING,
  PLAY_LIST_TYPE.PARTY,
  PLAY_LIST_TYPE.UNKNOW,
];

export default PLAY_LIST_TYPE;
