enum SONG_TYPE {
  LOFI = "LOFI",
  SYNTHWAVE = "SYNTHWAVE",
  POP = "POP",
  ROCK = "ROCK",
  CLASSIC = "CLASSIC",
  BOLERO = "BOLERO",
  ELECTRIC = "ELECTRIC",
  OTHERS = "OTHERS",
}

export const songTypeArray: SONG_TYPE[] = [
  SONG_TYPE.LOFI,
  SONG_TYPE.SYNTHWAVE,
  SONG_TYPE.POP,
  SONG_TYPE.ROCK,
  SONG_TYPE.CLASSIC,
  SONG_TYPE.BOLERO,
  SONG_TYPE.ELECTRIC,
  SONG_TYPE.OTHERS,
];

export default SONG_TYPE;
